// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> ping() => RustLib.instance.api.crateApiPing();

Future<String> checkDbHealth() => RustLib.instance.api.crateApiCheckDbHealth();

Future<String> getOnboardingStep() =>
    RustLib.instance.api.crateApiGetOnboardingStep();

Future<String> setOnboardingStep({required String step}) =>
    RustLib.instance.api.crateApiSetOnboardingStep(step: step);

Future<String> getStartupState() =>
    RustLib.instance.api.crateApiGetStartupState();

Future<String> createUserProfile(
        {required String username,
        required String nativeLang,
        required String targetLang,
        required String avatar,
        required int age,
        required String country,
        required String timezone,
        required int dailyMinutes}) =>
    RustLib.instance.api.crateApiCreateUserProfile(
        username: username,
        nativeLang: nativeLang,
        targetLang: targetLang,
        avatar: avatar,
        age: age,
        country: country,
        timezone: timezone,
        dailyMinutes: dailyMinutes);

Future<String> getActiveUser() => RustLib.instance.api.crateApiGetActiveUser();

Future<String> getAvailableScenarios() =>
    RustLib.instance.api.crateApiGetAvailableScenarios();

Future<String> startConversation({required String scenarioId}) =>
    RustLib.instance.api.crateApiStartConversation(scenarioId: scenarioId);

Future<String> sendDialogueTurn(
        {required String conversationId, required String text}) =>
    RustLib.instance.api
        .crateApiSendDialogueTurn(conversationId: conversationId, text: text);

Future<String> getConversationHistory({required String conversationId}) =>
    RustLib.instance.api
        .crateApiGetConversationHistory(conversationId: conversationId);

Future<String> installModel(
        {required String name,
        required String version,
        required List<int> content}) =>
    RustLib.instance.api
        .crateApiInstallModel(name: name, version: version, content: content);

Future<String> listInstalledModels() =>
    RustLib.instance.api.crateApiListInstalledModels();

Future<String> getSystemResourceBudget() =>
    RustLib.instance.api.crateApiGetSystemResourceBudget();

Future<String> getAnalyticsSnapshot() =>
    RustLib.instance.api.crateApiGetAnalyticsSnapshot();

Future<String> queryCapability({required String capName}) =>
    RustLib.instance.api.crateApiQueryCapability(capName: capName);

Future<String> getModelRegistry() =>
    RustLib.instance.api.crateApiGetModelRegistry();

Future<String> transcribeAudio({required List<int> audioBytes}) =>
    RustLib.instance.api.crateApiTranscribeAudio(audioBytes: audioBytes);

Future<Uint8List> synthesizeSpeech({required String text}) =>
    RustLib.instance.api.crateApiSynthesizeSpeech(text: text);

Future<String> getRuntimeDiagnostics() =>
    RustLib.instance.api.crateApiGetRuntimeDiagnostics();

Future<String> shutdownEngine() =>
    RustLib.instance.api.crateApiShutdownEngine();
