name: dilang_storage
description: Pure Dart Storage Infrastructure & Repository Contracts for DiLang. Decoupled from Domain.
version: 1.0.0
publish_to: 'none'
resolution: workspace
homepage: https://github.com/dilang/dilang

environment:
  sdk: '^3.5.0'

dependencies:
  dilang_core: ^1.0.0
  dilang_language: ^1.0.0
  dilang_learner: ^1.0.0
  dilang_memory: ^1.0.0
  meta: ^1.11.0
  equatable: ^2.0.5
  sqlite3: ^2.4.5
  crypto: ^3.0.3
  path: ^1.9.0


dev_dependencies:
  test: ^1.24.0
