class LanguageDescriptor {
  final String code;
  final String nativeName;
  final String englishName;
  final String script;
  final bool rtl;
  final String ttsVoice;
  final String sttModel;
  final String dictionary;
  final String phraseDb;
  final String morphology;
  final String locale;
  final String fontFamily;

  const LanguageDescriptor({
    required this.code,
    required this.nativeName,
    required this.englishName,
    required this.script,
    required this.rtl,
    required this.ttsVoice,
    required this.sttModel,
    required this.dictionary,
    required this.phraseDb,
    required this.morphology,
    required this.locale,
    required this.fontFamily,
  });

  factory LanguageDescriptor.fromJson(Map<String, dynamic> json) {
    return LanguageDescriptor(
      code: json['code'] ?? '',
      nativeName: json['native_name'] ?? '',
      englishName: json['english_name'] ?? '',
      script: json['script'] ?? 'Latin',
      rtl: json['rtl'] ?? false,
      ttsVoice: json['tts_voice'] ?? '',
      sttModel: json['stt_model'] ?? '',
      dictionary: json['dictionary'] ?? '',
      phraseDb: json['phrase_db'] ?? '',
      morphology: json['morphology'] ?? '',
      locale: json['locale'] ?? 'en_US',
      fontFamily: json['font_family'] ?? 'Inter',
    );
  }
}

class AppLanguageRegistry {
  static const List<LanguageDescriptor> supportedLanguages = [
    LanguageDescriptor(
      code: 'en',
      nativeName: 'English',
      englishName: 'English',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-en_US-lessac-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-en.sqlite',
      phraseDb: 'phrases-en.sqlite',
      morphology: 'morph-en.json',
      locale: 'en_US',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'de',
      nativeName: 'Deutsch',
      englishName: 'German',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-de_DE-thorsten-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-de.sqlite',
      phraseDb: 'phrases-de.sqlite',
      morphology: 'morph-de.json',
      locale: 'de_DE',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'fr',
      nativeName: 'Français',
      englishName: 'French',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-fr_FR-siwis-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-fr.sqlite',
      phraseDb: 'phrases-fr.sqlite',
      morphology: 'morph-fr.json',
      locale: 'fr_FR',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'es',
      nativeName: 'Español',
      englishName: 'Spanish',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-es_ES-davefx-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-es.sqlite',
      phraseDb: 'phrases-es.sqlite',
      morphology: 'morph-es.json',
      locale: 'es_ES',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'it',
      nativeName: 'Italiano',
      englishName: 'Italian',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-it_IT-riccardo-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-it.sqlite',
      phraseDb: 'phrases-it.sqlite',
      morphology: 'morph-it.json',
      locale: 'it_IT',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'pt',
      nativeName: 'Português',
      englishName: 'Portuguese',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-pt_PT-tugao-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-pt.sqlite',
      phraseDb: 'phrases-pt.sqlite',
      morphology: 'morph-pt.json',
      locale: 'pt_PT',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'nl',
      nativeName: 'Nederlands',
      englishName: 'Dutch',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-nl_NL-rdh-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-nl.sqlite',
      phraseDb: 'phrases-nl.sqlite',
      morphology: 'morph-nl.json',
      locale: 'nl_NL',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'pl',
      nativeName: 'Polski',
      englishName: 'Polish',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-pl_PL-darkzar-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-pl.sqlite',
      phraseDb: 'phrases-pl.sqlite',
      morphology: 'morph-pl.json',
      locale: 'pl_PL',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'ru',
      nativeName: 'Русский',
      englishName: 'Russian',
      script: 'Cyrillic',
      rtl: false,
      ttsVoice: 'piper-ru_RU-denis-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-ru.sqlite',
      phraseDb: 'phrases-ru.sqlite',
      morphology: 'morph-ru.json',
      locale: 'ru_RU',
      fontFamily: 'Roboto',
    ),
    LanguageDescriptor(
      code: 'zh',
      nativeName: '中文',
      englishName: 'Chinese',
      script: 'Han',
      rtl: false,
      ttsVoice: 'piper-zh_CN-huayan-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-zh.sqlite',
      phraseDb: 'phrases-zh.sqlite',
      morphology: 'morph-zh.json',
      locale: 'zh_CN',
      fontFamily: 'Noto Sans SC',
    ),
    LanguageDescriptor(
      code: 'ja',
      nativeName: '日本語',
      englishName: 'Japanese',
      script: 'Kana/Kanji',
      rtl: false,
      ttsVoice: 'piper-ja_JP-takumi-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-ja.sqlite',
      phraseDb: 'phrases-ja.sqlite',
      morphology: 'morph-ja.json',
      locale: 'ja_JP',
      fontFamily: 'Noto Sans JP',
    ),
    LanguageDescriptor(
      code: 'ko',
      nativeName: '한국어',
      englishName: 'Korean',
      script: 'Hangul',
      rtl: false,
      ttsVoice: 'piper-ko_KR-hyunjun-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-ko.sqlite',
      phraseDb: 'phrases-ko.sqlite',
      morphology: 'morph-ko.json',
      locale: 'ko_KR',
      fontFamily: 'Noto Sans KR',
    ),
    LanguageDescriptor(
      code: 'hi',
      nativeName: 'हिन्दी',
      englishName: 'Hindi',
      script: 'Devanagari',
      rtl: false,
      ttsVoice: 'piper-hi_IN-priyam-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-hi.sqlite',
      phraseDb: 'phrases-hi.sqlite',
      morphology: 'morph-hi.json',
      locale: 'hi_IN',
      fontFamily: 'Noto Sans Devanagari',
    ),
    LanguageDescriptor(
      code: 'ar',
      nativeName: 'العربية',
      englishName: 'Arabic',
      script: 'Arabic',
      rtl: true,
      ttsVoice: 'piper-ar_JO-kareem-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-ar.sqlite',
      phraseDb: 'phrases-ar.sqlite',
      morphology: 'morph-ar.json',
      locale: 'ar_SA',
      fontFamily: 'Noto Sans Arabic',
    ),
    LanguageDescriptor(
      code: 'tr',
      nativeName: 'Türkçe',
      englishName: 'Turkish',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-tr_TR-dfki-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-tr.sqlite',
      phraseDb: 'phrases-tr.sqlite',
      morphology: 'morph-tr.json',
      locale: 'tr_TR',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'vi',
      nativeName: 'Tiếng Việt',
      englishName: 'Vietnamese',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-vi_VN-25hours-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-vi.sqlite',
      phraseDb: 'phrases-vi.sqlite',
      morphology: 'morph-vi.json',
      locale: 'vi_VN',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'th',
      nativeName: 'ไทย',
      englishName: 'Thai',
      script: 'Thai',
      rtl: false,
      ttsVoice: 'piper-th_TH-pattara-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-th.sqlite',
      phraseDb: 'phrases-th.sqlite',
      morphology: 'morph-th.json',
      locale: 'th_TH',
      fontFamily: 'Noto Sans Thai',
    ),
    LanguageDescriptor(
      code: 'id',
      nativeName: 'Bahasa Indonesia',
      englishName: 'Indonesian',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-id_ID-arvis-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-id.sqlite',
      phraseDb: 'phrases-id.sqlite',
      morphology: 'morph-id.json',
      locale: 'id_ID',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'sv',
      nativeName: 'Svenska',
      englishName: 'Swedish',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-sv_SE-nst-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-sv.sqlite',
      phraseDb: 'phrases-sv.sqlite',
      morphology: 'morph-sv.json',
      locale: 'sv_SE',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'no',
      nativeName: 'Norsk',
      englishName: 'Norwegian',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-no_NO-tore-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-no.sqlite',
      phraseDb: 'phrases-no.sqlite',
      morphology: 'morph-no.json',
      locale: 'nb_NO',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'da',
      nativeName: 'Dansk',
      englishName: 'Danish',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-da_DK-toke-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-da.sqlite',
      phraseDb: 'phrases-da.sqlite',
      morphology: 'morph-da.json',
      locale: 'da_DK',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'fi',
      nativeName: 'Suomi',
      englishName: 'Finnish',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-fi_FI-harri-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-fi.sqlite',
      phraseDb: 'phrases-fi.sqlite',
      morphology: 'morph-fi.json',
      locale: 'fi_FI',
      fontFamily: 'Inter',
    ),
    LanguageDescriptor(
      code: 'el',
      nativeName: 'Ελληνικά',
      englishName: 'Greek',
      script: 'Greek',
      rtl: false,
      ttsVoice: 'piper-el_GR-rapunzelina-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-el.sqlite',
      phraseDb: 'phrases-el.sqlite',
      morphology: 'morph-el.json',
      locale: 'el_GR',
      fontFamily: 'Roboto',
    ),
    LanguageDescriptor(
      code: 'cs',
      nativeName: 'Čeština',
      englishName: 'Czech',
      script: 'Latin',
      rtl: false,
      ttsVoice: 'piper-cs_CZ-jirka-medium',
      sttModel: 'whisper-base',
      dictionary: 'dict-cs.sqlite',
      phraseDb: 'phrases-cs.sqlite',
      morphology: 'morph-cs.json',
      locale: 'cs_CZ',
      fontFamily: 'Inter',
    ),
  ];

  static LanguageDescriptor find(String query) {
    final clean = query.trim().toLowerCase();
    return supportedLanguages.firstWhere(
      (l) => l.code == clean || l.englishName.toLowerCase() == clean || l.nativeName.toLowerCase() == clean,
      orElse: () => supportedLanguages.first,
    );
  }
}
