name: dilang

packages:
  - packages/*
  - apps/*
  - benchmarks

command:
  bootstrap:
    dontGeneratePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
    description: Run static analysis across all packages in workspace.

  test:
    exec: dart test
    description: Run unit test suites across all packages in workspace.

  clean:
    exec: dart clean
    description: Clean build artifacts across all packages.
