name: dilang
packages:
  - packages/*
  - apps/*

command:
  bootstrap:
    usePubGet: true

scripts:
  analyze:
    run: melos exec -- "dart analyze ."
    description: Run static analysis across all packages in workspace.

  test:
    run: melos exec -- "dart test"
    description: Run unit test suites across all packages in workspace.

  clean:
    run: melos exec -- "dart clean"
    description: Clean build artifacts across all packages.
