[package]
name = "dilang_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
flutter_rust_bridge.workspace = true
dilang_fsrs = { path = "../dilang_fsrs" }
dilang_sqlite = { path = "../dilang_sqlite" }
dilang_models = { path = "../dilang_models" }

[lib]
crate-type = ["cdylib", "rlib"]
