import 'package:flutter/material.dart';
import '../infrastructure/language_registry.dart';

class LocalizationManager {
  final String sourceLanguage;

  LocalizationManager({required this.sourceLanguage});

  LanguageDescriptor get descriptor => AppLanguageRegistry.find(sourceLanguage);
  TextDirection get textDirection => descriptor.rtl ? TextDirection.rtl : TextDirection.ltr;

  // Localized UI dictionary
  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_title': 'DiLang',
      'welcome_title': 'Welcome, {username}!',
      'learn_tab': 'Learn',
      'speak_tab': 'Speak',
      'settings_tab': 'Settings',
      'interactive_session': 'Interactive AI Dialogue Session',
      'practice_speaking': 'Practice speaking {targetLang} offline with Qwen3-0.6B LLM',
      'local_ai_models': 'Local AI Inference Models',
      'model_center': 'Model Center',
      'learning_analytics': 'Learning Analytics',
      'vocab_known': 'Vocabulary Known',
      'grammar_concepts': 'Grammar Concepts',
      'sessions_completed': 'Sessions Completed',
      'srs_reviews_due': 'SRS Reviews Due',
      'download_missing_models': 'Download Missing Models in Settings',
      'complete_onboarding': 'Complete Onboarding',
      'download_later': 'Download Later in Settings',
      'retry_download': 'Retry Model Download',
      'hardware_validation': 'Hardware Validation',
      'runtime_diagnostics': 'Runtime Diagnostics',
      'developer_showcase': 'Developer Showcase',
      'learner_profile': 'Learner Profile',
      'model_download_center': 'Model Download Center',
    },
    'de': {
      'app_title': 'DiLang',
      'welcome_title': 'Willkommen, {username}!',
      'learn_tab': 'Lernen',
      'speak_tab': 'Sprechen',
      'settings_tab': 'Einstellungen',
      'interactive_session': 'Interaktive KI-Dialogsitzung',
      'practice_speaking': 'Üben Sie {targetLang} offline mit Qwen3-0.6B LLM',
      'local_ai_models': 'Lokale KI-Inferenzmodelle',
      'model_center': 'Modell-Zentrum',
      'learning_analytics': 'Lernanalysen',
      'vocab_known': 'Bekannte Vokabeln',
      'grammar_concepts': 'Grammatikkonzepte',
      'sessions_completed': 'Abgeschlossene Sitzungen',
      'srs_reviews_due': 'Fällige Wiederholungen',
      'download_missing_models': 'Fehlende Modelle in Einstellungen herunterladen',
      'complete_onboarding': 'Onboarding abschließen',
      'download_later': 'Später in den Einstellungen herunterladen',
      'retry_download': 'Download erneut versuchen',
      'hardware_validation': 'Hardware-Validierung',
      'runtime_diagnostics': 'Laufzeit-Diagnose',
      'developer_showcase': 'Entwickler-Showcase',
      'learner_profile': 'Lerner-Profil',
      'model_download_center': 'Modell-Download-Zentrum',
    },
    'es': {
      'app_title': 'DiLang',
      'welcome_title': '¡Bienvenido, {username}!',
      'learn_tab': 'Aprender',
      'speak_tab': 'Hablar',
      'settings_tab': 'Ajustes',
      'interactive_session': 'Sesión de Diálogo con IA Interactiva',
      'practice_speaking': 'Practica hablar {targetLang} sin conexión con Qwen3-0.6B LLM',
      'local_ai_models': 'Modelos de Inferencia de IA Locales',
      'model_center': 'Centro de Modelos',
      'learning_analytics': 'Análisis de Aprendizaje',
      'vocab_known': 'Vocabulario Conocido',
      'grammar_concepts': 'Conceptos Gramaticales',
      'sessions_completed': 'Sesiones Completadas',
      'srs_reviews_due': 'Repasos Pendientes',
      'download_missing_models': 'Descargar Modelos Faltantes en Ajustes',
      'complete_onboarding': 'Completar Integración',
      'download_later': 'Descargar Más Tarde en Ajustes',
      'retry_download': 'Reintentar Descarga',
      'hardware_validation': 'Validación de Hardware',
      'runtime_diagnostics': 'Diagnóstico de Ejecución',
      'developer_showcase': 'Muestra para Desarrolladores',
      'learner_profile': 'Perfil del Estudiante',
      'model_download_center': 'Centro de Descarga de Modelos',
    },
    'fr': {
      'app_title': 'DiLang',
      'welcome_title': 'Bienvenue, {username} !',
      'learn_tab': 'Apprendre',
      'speak_tab': 'Parler',
      'settings_tab': 'Paramètres',
      'interactive_session': 'Session de Dialogue IA Interactive',
      'practice_speaking': 'Pratiquez l\'oral en {targetLang} hors ligne avec Qwen3-0.6B LLM',
      'local_ai_models': 'Modèles d\'Inférence IA Locaux',
      'model_center': 'Centre de Modèles',
      'learning_analytics': 'Analyses d\'Apprentissage',
      'vocab_known': 'Vocabulaire Connu',
      'grammar_concepts': 'Concepts Grammaticaux',
      'sessions_completed': 'Sessions Terminées',
      'srs_reviews_due': 'Révisions à Faire',
      'download_missing_models': 'Télécharger les modèles manquants',
      'complete_onboarding': 'Terminer l\'Intégration',
      'download_later': 'Télécharger plus tard',
      'retry_download': 'Réessayer le Téléchargement',
      'hardware_validation': 'Validation Matérielle',
      'runtime_diagnostics': 'Diagnostics d\'Exécution',
      'developer_showcase': 'Vitrines Développeur',
      'learner_profile': 'Profil de l\'Apprenant',
      'model_download_center': 'Centre de Téléchargement de Modèles',
    },
    'hi': {
      'app_title': 'DiLang',
      'welcome_title': 'स्वागत है, {username}!',
      'learn_tab': 'सीखें',
      'speak_tab': 'बोलें',
      'settings_tab': 'सेटिंग्स',
      'interactive_session': 'इंटरएक्टिव AI संवाद सत्र',
      'practice_speaking': 'Qwen3-0.6B LLM के साथ ऑफ़लाइन {targetLang} बोलने का अभ्यास करें',
      'local_ai_models': 'लोकल AI मॉडल',
      'model_center': 'मॉडल केंद्र',
      'learning_analytics': 'सीखने का विश्लेषण',
      'vocab_known': 'ज्ञात शब्दावली',
      'grammar_concepts': 'व्याकरण की अवधारणाएं',
      'sessions_completed': 'पूरे किए गए सत्र',
      'srs_reviews_due': 'समीक्षा बाकी',
      'download_missing_models': 'सेटिंग्स में छूटे हुए मॉडल डाउनलोड करें',
      'complete_onboarding': 'ऑनबोर्डिंग पूरी करें',
      'download_later': 'बाद में सेटिंग्स में डाउनलोड करें',
      'retry_download': 'पुनः प्रयास करें',
      'hardware_validation': 'हार्डवेयर सत्यापन',
      'runtime_diagnostics': 'रनटाइम निदान',
      'developer_showcase': 'डेवलपर शोकेस',
      'learner_profile': 'शिक्षार्थी प्रोफ़ाइल',
      'model_download_center': 'मॉडल डाउनलोड केंद्र',
    },
    'ar': {
      'app_title': 'DiLang',
      'welcome_title': 'مرحباً، {username}!',
      'learn_tab': 'تعلم',
      'speak_tab': 'تحدث',
      'settings_tab': 'الإعدادات',
      'interactive_session': 'جلسة حوار تفاعلية بالذكاء الاصطناعي',
      'practice_speaking': 'تدرّب على التحدث باللغة {targetLang} دون اتصال مع Qwen3-0.6B LLM',
      'local_ai_models': 'نماذج الذكاء الاصطناعي المحلية',
      'model_center': 'مركز النماذج',
      'learning_analytics': 'تحليلات التعلم',
      'vocab_known': 'المفردات المكتسبة',
      'grammar_concepts': 'قواعد اللغة',
      'sessions_completed': 'الجلسات المكتملة',
      'srs_reviews_due': 'المراجعات المستحقة',
      'download_missing_models': 'تحميل النماذج المفقودة من الإعدادات',
      'complete_onboarding': 'إكمال الإعداد',
      'download_later': 'التحميل لاحقاً في الإعدادات',
      'retry_download': 'إعادة محاولة التحميل',
      'hardware_validation': 'التحقق من الأجهزة',
      'runtime_diagnostics': 'تشخيص التشغيل',
      'developer_showcase': 'معرض المطورين',
      'learner_profile': 'ملف المتعلم',
      'model_download_center': 'مركز تحميل النماذج',
    },
    'ja': {
      'app_title': 'DiLang',
      'welcome_title': 'ようこそ、{username}さん！',
      'learn_tab': '学習',
      'speak_tab': '会話',
      'settings_tab': '設定',
      'interactive_session': 'インタラクティブAI会話セッション',
      'practice_speaking': 'Qwen3-0.6B LLMでオフラインで{targetLang}スピーキング練習',
      'local_ai_models': 'ローカルAI推論モデル',
      'model_center': 'モデルセンター',
      'learning_analytics': '学習アナリティクス',
      'vocab_known': '習得語彙数',
      'grammar_concepts': '文法コンセプト',
      'sessions_completed': '完了セッション',
      'srs_reviews_due': '復習カード数',
      'download_missing_models': '設定で未ダウンロードモデルを取得',
      'complete_onboarding': 'オンボーディング完了',
      'download_later': 'あとで設定からダウンロード',
      'retry_download': 'ダウンロード再試行',
      'hardware_validation': 'ハードウェア検証',
      'runtime_diagnostics': 'ランタイム診断',
      'developer_showcase': '開発者ショーケース',
      'learner_profile': '学習者プロフィール',
      'model_download_center': 'モデルダウンロードセンター',
    },
  };

  String translate(String key, {Map<String, String>? args}) {
    final langCode = descriptor.code;
    final map = _localizedStrings[langCode] ?? _localizedStrings['en']!;
    String val = map[key] ?? _localizedStrings['en']![key] ?? key;

    if (args != null) {
      args.forEach((k, v) {
        val = val.replaceAll('{$k}', v);
      });
    }
    return val;
  }
}
