//! Unified 24-Language Registry Core
//! Provides a single source of truth for supported source & target languages, scripts, RTL layout, TTS/STT defaults, and localization metadata.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LanguageDescriptor {
    pub code: String,
    pub native_name: String,
    pub english_name: String,
    pub script: String,
    pub rtl: bool,
    pub tts_voice: String,
    pub stt_model: String,
    pub dictionary: String,
    pub phrase_db: String,
    pub morphology: String,
    pub plural_rules: String,
    pub date_format: String,
    pub number_format: String,
    pub locale: String,
    pub font_family: String,
}

pub struct LanguageRegistry;

impl LanguageRegistry {
    pub fn get_all_languages() -> Vec<LanguageDescriptor> {
        vec![
            LanguageDescriptor {
                code: "en".into(),
                native_name: "English".into(),
                english_name: "English".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-en_US-lessac-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-en.sqlite".into(),
                phrase_db: "phrases-en.sqlite".into(),
                morphology: "morph-en.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "MM/DD/YYYY".into(),
                number_format: "#,##0.00".into(),
                locale: "en_US".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "de".into(),
                native_name: "Deutsch".into(),
                english_name: "German".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-de_DE-thorsten-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-de.sqlite".into(),
                phrase_db: "phrases-de.sqlite".into(),
                morphology: "morph-de.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "de_DE".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "fr".into(),
                native_name: "Français".into(),
                english_name: "French".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-fr_FR-siwis-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-fr.sqlite".into(),
                phrase_db: "phrases-fr.sqlite".into(),
                morphology: "morph-fr.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "# ##0,00".into(),
                locale: "fr_FR".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "es".into(),
                native_name: "Español".into(),
                english_name: "Spanish".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-es_ES-davefx-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-es.sqlite".into(),
                phrase_db: "phrases-es.sqlite".into(),
                morphology: "morph-es.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "es_ES".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "it".into(),
                native_name: "Italiano".into(),
                english_name: "Italian".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-it_IT-riccardo-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-it.sqlite".into(),
                phrase_db: "phrases-it.sqlite".into(),
                morphology: "morph-it.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "it_IT".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "pt".into(),
                native_name: "Português".into(),
                english_name: "Portuguese".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-pt_PT-tugao-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-pt.sqlite".into(),
                phrase_db: "phrases-pt.sqlite".into(),
                morphology: "morph-pt.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "pt_PT".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "nl".into(),
                native_name: "Nederlands".into(),
                english_name: "Dutch".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-nl_NL-rdh-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-nl.sqlite".into(),
                phrase_db: "phrases-nl.sqlite".into(),
                morphology: "morph-nl.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD-MM-YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "nl_NL".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "pl".into(),
                native_name: "Polski".into(),
                english_name: "Polish".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-pl_PL-darkzar-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-pl.sqlite".into(),
                phrase_db: "phrases-pl.sqlite".into(),
                morphology: "morph-pl.json".into(),
                plural_rules: "cardinal_few_many".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "# ##0,00".into(),
                locale: "pl_PL".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "ru".into(),
                native_name: "Русский".into(),
                english_name: "Russian".into(),
                script: "Cyrillic".into(),
                rtl: false,
                tts_voice: "piper-ru_RU-denis-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-ru.sqlite".into(),
                phrase_db: "phrases-ru.sqlite".into(),
                morphology: "morph-ru.json".into(),
                plural_rules: "cardinal_few_many".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "# ##0,00".into(),
                locale: "ru_RU".into(),
                font_family: "Roboto".into(),
            },
            LanguageDescriptor {
                code: "zh".into(),
                native_name: "中文".into(),
                english_name: "Chinese".into(),
                script: "Han".into(),
                rtl: false,
                tts_voice: "piper-zh_CN-huayan-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-zh.sqlite".into(),
                phrase_db: "phrases-zh.sqlite".into(),
                morphology: "morph-zh.json".into(),
                plural_rules: "cardinal_other".into(),
                date_format: "YYYY/MM/DD".into(),
                number_format: "#,##0.00".into(),
                locale: "zh_CN".into(),
                font_family: "Noto Sans SC".into(),
            },
            LanguageDescriptor {
                code: "ja".into(),
                native_name: "日本語".into(),
                english_name: "Japanese".into(),
                script: "Kana/Kanji".into(),
                rtl: false,
                tts_voice: "piper-ja_JP-takumi-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-ja.sqlite".into(),
                phrase_db: "phrases-ja.sqlite".into(),
                morphology: "morph-ja.json".into(),
                plural_rules: "cardinal_other".into(),
                date_format: "YYYY/MM/DD".into(),
                number_format: "#,##0.00".into(),
                locale: "ja_JP".into(),
                font_family: "Noto Sans JP".into(),
            },
            LanguageDescriptor {
                code: "ko".into(),
                native_name: "한국어".into(),
                english_name: "Korean".into(),
                script: "Hangul".into(),
                rtl: false,
                tts_voice: "piper-ko_KR-hyunjun-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-ko.sqlite".into(),
                phrase_db: "phrases-ko.sqlite".into(),
                morphology: "morph-ko.json".into(),
                plural_rules: "cardinal_other".into(),
                date_format: "YYYY. MM. DD.".into(),
                number_format: "#,##0.00".into(),
                locale: "ko_KR".into(),
                font_family: "Noto Sans KR".into(),
            },
            LanguageDescriptor {
                code: "hi".into(),
                native_name: "हिन्दी".into(),
                english_name: "Hindi".into(),
                script: "Devanagari".into(),
                rtl: false,
                tts_voice: "piper-hi_IN-priyam-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-hi.sqlite".into(),
                phrase_db: "phrases-hi.sqlite".into(),
                morphology: "morph-hi.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#,##,##0.00".into(),
                locale: "hi_IN".into(),
                font_family: "Noto Sans Devanagari".into(),
            },
            LanguageDescriptor {
                code: "ar".into(),
                native_name: "العربية".into(),
                english_name: "Arabic".into(),
                script: "Arabic".into(),
                rtl: true,
                tts_voice: "piper-ar_JO-kareem-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-ar.sqlite".into(),
                phrase_db: "phrases-ar.sqlite".into(),
                morphology: "morph-ar.json".into(),
                plural_rules: "cardinal_arabic".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#,##0.00".into(),
                locale: "ar_SA".into(),
                font_family: "Noto Sans Arabic".into(),
            },
            LanguageDescriptor {
                code: "tr".into(),
                native_name: "Türkçe".into(),
                english_name: "Turkish".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-tr_TR-dfki-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-tr.sqlite".into(),
                phrase_db: "phrases-tr.sqlite".into(),
                morphology: "morph-tr.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "tr_TR".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "vi".into(),
                native_name: "Tiếng Việt".into(),
                english_name: "Vietnamese".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-vi_VN-25hours-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-vi.sqlite".into(),
                phrase_db: "phrases-vi.sqlite".into(),
                morphology: "morph-vi.json".into(),
                plural_rules: "cardinal_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "vi_VN".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "th".into(),
                native_name: "ไทย".into(),
                english_name: "Thai".into(),
                script: "Thai".into(),
                rtl: false,
                tts_voice: "piper-th_TH-pattara-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-th.sqlite".into(),
                phrase_db: "phrases-th.sqlite".into(),
                morphology: "morph-th.json".into(),
                plural_rules: "cardinal_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#,##0.00".into(),
                locale: "th_TH".into(),
                font_family: "Noto Sans Thai".into(),
            },
            LanguageDescriptor {
                code: "id".into(),
                native_name: "Bahasa Indonesia".into(),
                english_name: "Indonesian".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-id_ID-arvis-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-id.sqlite".into(),
                phrase_db: "phrases-id.sqlite".into(),
                morphology: "morph-id.json".into(),
                plural_rules: "cardinal_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "id_ID".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "sv".into(),
                native_name: "Svenska".into(),
                english_name: "Swedish".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-sv_SE-nst-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-sv.sqlite".into(),
                phrase_db: "phrases-sv.sqlite".into(),
                morphology: "morph-sv.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "YYYY-MM-DD".into(),
                number_format: "# ##0,00".into(),
                locale: "sv_SE".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "no".into(),
                native_name: "Norsk".into(),
                english_name: "Norwegian".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-no_NO-tore-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-no.sqlite".into(),
                phrase_db: "phrases-no.sqlite".into(),
                morphology: "morph-no.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "# ##0,00".into(),
                locale: "nb_NO".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "da".into(),
                native_name: "Dansk".into(),
                english_name: "Danish".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-da_DK-toke-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-da.sqlite".into(),
                phrase_db: "phrases-da.sqlite".into(),
                morphology: "morph-da.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "da_DK".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "fi".into(),
                native_name: "Suomi".into(),
                english_name: "Finnish".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-fi_FI-harri-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-fi.sqlite".into(),
                phrase_db: "phrases-fi.sqlite".into(),
                morphology: "morph-fi.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD.MM.YYYY".into(),
                number_format: "# ##0,00".into(),
                locale: "fi_FI".into(),
                font_family: "Inter".into(),
            },
            LanguageDescriptor {
                code: "el".into(),
                native_name: "Ελληνικά".into(),
                english_name: "Greek".into(),
                script: "Greek".into(),
                rtl: false,
                tts_voice: "piper-el_GR-rapunzelina-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-el.sqlite".into(),
                phrase_db: "phrases-el.sqlite".into(),
                morphology: "morph-el.json".into(),
                plural_rules: "cardinal_one_other".into(),
                date_format: "DD/MM/YYYY".into(),
                number_format: "#.##0,00".into(),
                locale: "el_GR".into(),
                font_family: "Roboto".into(),
            },
            LanguageDescriptor {
                code: "cs".into(),
                native_name: "Čeština".into(),
                english_name: "Czech".into(),
                script: "Latin".into(),
                rtl: false,
                tts_voice: "piper-cs_CZ-jirka-medium".into(),
                stt_model: "whisper-base".into(),
                dictionary: "dict-cs.sqlite".into(),
                phrase_db: "phrases-cs.sqlite".into(),
                morphology: "morph-cs.json".into(),
                plural_rules: "cardinal_few_many".into(),
                date_format: "DD. MM. YYYY".into(),
                number_format: "# ##0,00".into(),
                locale: "cs_CZ".into(),
                font_family: "Inter".into(),
            },
        ]
    }

    pub fn find_by_code(code: &str) -> Option<LanguageDescriptor> {
        let clean = code.trim().to_lowercase();
        Self::get_all_languages().into_iter().find(|l| l.code.to_lowercase() == clean || l.english_name.to_lowercase() == clean)
    }
}
