// Auto-generated by flutter_rust_bridge_codegen.
// DO NOT EDIT THIS FILE MANUALLY.

#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure_call,
    clippy::needless_return,
    clippy::too_many_arguments,
    clippy::redundant_locals,
    clippy::new_without_default,
    clippy::warn_on_violation,
    clippy::all
)]

pub fn ping_impl() -> String {
    crate::api::ping()
}

pub fn check_db_health_impl() -> String {
    crate::api::check_db_health()
}
