// Auto-generated by flutter_rust_bridge_codegen.
// DO NOT EDIT THIS FILE MANUALLY.

#![allow(
    non_camel_case_types,
    unused,
    unknown_lints,
    clippy::redundant_closure_call,
    clippy::needless_return,
    clippy::too_many_arguments,
    clippy::redundant_locals,
    clippy::new_without_default,
    clippy::all
)]

pub fn ping_impl() -> String {
    crate::api::ping()
}

pub fn check_db_health_impl() -> String {
    crate::api::check_db_health()
}

pub fn get_startup_state_impl() -> String {
    crate::api::get_startup_state()
}

pub fn create_user_profile_impl(
    username: String,
    native_lang: String,
    target_lang: String,
    avatar: String,
    age: u32,
    country: String,
    timezone: String,
    daily_minutes: u32,
) -> String {
    crate::api::create_user_profile(
        username,
        native_lang,
        target_lang,
        avatar,
        age,
        country,
        timezone,
        daily_minutes,
    )
}

pub fn get_active_user_impl() -> String {
    crate::api::get_active_user()
}

pub fn get_available_scenarios_impl() -> String {
    crate::api::get_available_scenarios()
}

pub fn start_conversation_impl(scenario_id: String) -> String {
    crate::api::start_conversation(scenario_id)
}

pub fn send_dialogue_turn_impl(conversation_id: String, text: String) -> String {
    crate::api::send_dialogue_turn(conversation_id, text)
}

pub fn get_conversation_history_impl(conversation_id: String) -> String {
    crate::api::get_conversation_history(conversation_id)
}

pub fn install_model_impl(name: String, version: String, content: Vec<u8>) -> String {
    crate::api::install_model(name, version, content)
}

pub fn list_installed_models_impl() -> String {
    crate::api::list_installed_models()
}

pub fn get_system_resource_budget_impl() -> String {
    crate::api::get_system_resource_budget()
}

pub fn get_analytics_snapshot_impl() -> String {
    crate::api::get_analytics_snapshot()
}

pub fn query_capability_impl(cap_name: String) -> String {
    crate::api::query_capability(cap_name)
}

pub fn shutdown_engine_impl() -> String {
    crate::api::shutdown_engine()
}
